# dnsPolicy set to default ensures karpenter pods do not rely on coredns for IP translation
dnsPolicy: Default
replicas: 3
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: DoesNotExist
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
tolerations:
  - key: "karpenter"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}
controller:
  image:
    repository: ${account_id}.dkr.ecr.${region}.amazonaws.com/karpenter/controller
    tag: ${image_tag}
    digest: ${image_digest}
settings:
  clusterName: ${cluster_name}
  clusterEndpoint: ${cluster_endpoint}
  interruptionQueue: ${queue_name}
  